# Generated by Django 5.1.6 on 2025-02-25 18:23

import apps.user.models.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_process', '0004_groupapplication_reject_reason'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата назначения роли')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия роли')),
                ('playing_level', models.CharField(choices=[('beginner', 'Начинающий'), ('player', 'Играющий'), ('pro', 'Профессионал')], verbose_name='Уровень')),
                ('groups', models.ManyToManyField(blank=True, related_name='athletes', to='training_process.group', verbose_name='Группы')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Спортсмен',
                'verbose_name_plural': 'Спортсмены',
            },
            managers=[
                ('objects', apps.user.models.managers.AthleteManager()),
            ],
        ),
    ]
