# Generated by Django 5.1.6 on 2025-02-15 17:26

import apps.user.models.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='administrator',
            managers=[
                ('objects', apps.user.models.managers.AdministratorManager()),
            ],
        ),
    ]
