# Generated by Django 5.1.6 on 2025-07-08 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='coach_experience',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Тренерский стаж (полных лет) на дату приема'),
        ),
    ]
