# Generated by Django 5.1.6 on 2025-02-20 18:07

import apps.user.models.managers
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_administrator_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата назначения роли')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата окончания действия роли')),
                ('position', models.CharField(choices=[('instructor', 'Тренер-преподаватель'), ('senior', 'Старший тренер')], default='instructor', verbose_name='Должность')),
                ('judge_category', models.CharField(blank=True, choices=[('third', 'Судья 3-й категории'), ('second', 'Судья 2-й категории'), ('first', 'Судья 1-й категории'), ('highest', 'Судья высшей категории')], null=True, verbose_name='Судейская категория')),
                ('education', models.CharField(blank=True, max_length=300, null=True, verbose_name='Образование')),
                ('additional_info', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Дополнительная информация')),
                ('achievements', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Достижения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coaches', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'тренер',
                'verbose_name_plural': 'тренеры',
            },
            managers=[
                ('objects', apps.user.models.managers.CoachManager()),
            ],
        ),
    ]
