# Generated by Django 5.1.6 on 2025-02-22 12:35

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_administrator_options_alter_coach_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание')),
                ('min_participants', models.PositiveSmallIntegerField(default=6, verbose_name='Минимальное количество спортсменов')),
                ('max_participants', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(12)], verbose_name='Максимальное количество спортсменов')),
                ('playing_level', models.CharField(choices=[('beginner', 'Начинающий'), ('player', 'Играющий'), ('pro', 'Профессионал')], verbose_name='Уровень занимающихся')),
                ('training_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятница'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')]), size=None, verbose_name='Дни тренировок')),
                ('training_time', models.CharField(max_length=50, verbose_name='Время тренировок')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='user.coach', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
    ]
