# Generated by Django 5.1.6 on 2025-02-25 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_process', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время подачи заявки')),
                ('status', models.CharField(blank=True, choices=[('new', 'Новая'), ('approved', 'Подтвержденная'), ('reject', 'Отклоненная')], default='new', verbose_name='Статус заявки')),
                ('playing_level', models.CharField(choices=[('beginner', 'Начинающий'), ('player', 'Играющий'), ('pro', 'Профессионал')], verbose_name='Уровень занимающихся')),
                ('comment', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Комментарий к заявке')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_applications', to='training_process.group', verbose_name='Группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на присоединение к группе',
                'verbose_name_plural': 'Заявки на присоединение к группе',
            },
        ),
    ]
