# Generated by Django 5.1.6 on 2025-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_process', '0003_groupapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapplication',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Причина отклонения заявки'),
        ),
    ]
