# Generated by Django 5.1.6 on 2025-05-17 11:35

import apps.training_process.models.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_process', '0004_groupapplication_reject_reason'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='groupapplication',
            managers=[
                ('objects', apps.training_process.models.managers.GroupApplicationManager()),
            ],
        ),
    ]
